version: "3.3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - db
    volumes:
      - ./:/app

  nginx:
    image: nginx
    links:
      - app
    volumes:
      - ./:/app
      - .docker/nginx/conf:/etc/nginx/conf.d
      - .docker/nginx/log:/var/log/nginx
    ports:
      - "8080:80"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .docker/database/data:/var/lib/mysql
      - .docker/database/log:/var/log/mysql
